logging.level.springboot=debug
server.port=8082

# 开启 H2 控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 内嵌数据库配置
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:spring/tx/schema.sql