/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.demo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2026-04-20")
public class CollectionTask implements org.apache.thrift.TBase<CollectionTask, CollectionTask._Fields>, java.io.Serializable, Cloneable, Comparable<CollectionTask> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CollectionTask");

  private static final org.apache.thrift.protocol.TField TASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("taskId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField CUSTOMER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("customerId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OVERDUE_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("overdueAmount", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField OVERDUE_DAYS_FIELD_DESC = new org.apache.thrift.protocol.TField("overdueDays", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField PRIORITY_FIELD_DESC = new org.apache.thrift.protocol.TField("priority", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CollectionTaskStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CollectionTaskTupleSchemeFactory());
  }

  public long taskId; // required
  public String customerId; // required
  public double overdueAmount; // required
  public int overdueDays; // required
  public String priority; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TASK_ID((short)1, "taskId"),
    CUSTOMER_ID((short)2, "customerId"),
    OVERDUE_AMOUNT((short)3, "overdueAmount"),
    OVERDUE_DAYS((short)4, "overdueDays"),
    PRIORITY((short)5, "priority");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASK_ID
          return TASK_ID;
        case 2: // CUSTOMER_ID
          return CUSTOMER_ID;
        case 3: // OVERDUE_AMOUNT
          return OVERDUE_AMOUNT;
        case 4: // OVERDUE_DAYS
          return OVERDUE_DAYS;
        case 5: // PRIORITY
          return PRIORITY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TASKID_ISSET_ID = 0;
  private static final int __OVERDUEAMOUNT_ISSET_ID = 1;
  private static final int __OVERDUEDAYS_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASK_ID, new org.apache.thrift.meta_data.FieldMetaData("taskId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CUSTOMER_ID, new org.apache.thrift.meta_data.FieldMetaData("customerId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OVERDUE_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("overdueAmount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.OVERDUE_DAYS, new org.apache.thrift.meta_data.FieldMetaData("overdueDays", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PRIORITY, new org.apache.thrift.meta_data.FieldMetaData("priority", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CollectionTask.class, metaDataMap);
  }

  public CollectionTask() {
  }

  public CollectionTask(
    long taskId,
    String customerId,
    double overdueAmount,
    int overdueDays,
    String priority)
  {
    this();
    this.taskId = taskId;
    setTaskIdIsSet(true);
    this.customerId = customerId;
    this.overdueAmount = overdueAmount;
    setOverdueAmountIsSet(true);
    this.overdueDays = overdueDays;
    setOverdueDaysIsSet(true);
    this.priority = priority;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CollectionTask(CollectionTask other) {
    __isset_bitfield = other.__isset_bitfield;
    this.taskId = other.taskId;
    if (other.isSetCustomerId()) {
      this.customerId = other.customerId;
    }
    this.overdueAmount = other.overdueAmount;
    this.overdueDays = other.overdueDays;
    if (other.isSetPriority()) {
      this.priority = other.priority;
    }
  }

  public CollectionTask deepCopy() {
    return new CollectionTask(this);
  }

  @Override
  public void clear() {
    setTaskIdIsSet(false);
    this.taskId = 0;
    this.customerId = null;
    setOverdueAmountIsSet(false);
    this.overdueAmount = 0.0;
    setOverdueDaysIsSet(false);
    this.overdueDays = 0;
    this.priority = null;
  }

  public long getTaskId() {
    return this.taskId;
  }

  public CollectionTask setTaskId(long taskId) {
    this.taskId = taskId;
    setTaskIdIsSet(true);
    return this;
  }

  public void unsetTaskId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  /** Returns true if field taskId is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskId() {
    return EncodingUtils.testBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  public void setTaskIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TASKID_ISSET_ID, value);
  }

  public String getCustomerId() {
    return this.customerId;
  }

  public CollectionTask setCustomerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

  public void unsetCustomerId() {
    this.customerId = null;
  }

  /** Returns true if field customerId is set (has been assigned a value) and false otherwise */
  public boolean isSetCustomerId() {
    return this.customerId != null;
  }

  public void setCustomerIdIsSet(boolean value) {
    if (!value) {
      this.customerId = null;
    }
  }

  public double getOverdueAmount() {
    return this.overdueAmount;
  }

  public CollectionTask setOverdueAmount(double overdueAmount) {
    this.overdueAmount = overdueAmount;
    setOverdueAmountIsSet(true);
    return this;
  }

  public void unsetOverdueAmount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OVERDUEAMOUNT_ISSET_ID);
  }

  /** Returns true if field overdueAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetOverdueAmount() {
    return EncodingUtils.testBit(__isset_bitfield, __OVERDUEAMOUNT_ISSET_ID);
  }

  public void setOverdueAmountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OVERDUEAMOUNT_ISSET_ID, value);
  }

  public int getOverdueDays() {
    return this.overdueDays;
  }

  public CollectionTask setOverdueDays(int overdueDays) {
    this.overdueDays = overdueDays;
    setOverdueDaysIsSet(true);
    return this;
  }

  public void unsetOverdueDays() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OVERDUEDAYS_ISSET_ID);
  }

  /** Returns true if field overdueDays is set (has been assigned a value) and false otherwise */
  public boolean isSetOverdueDays() {
    return EncodingUtils.testBit(__isset_bitfield, __OVERDUEDAYS_ISSET_ID);
  }

  public void setOverdueDaysIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OVERDUEDAYS_ISSET_ID, value);
  }

  public String getPriority() {
    return this.priority;
  }

  public CollectionTask setPriority(String priority) {
    this.priority = priority;
    return this;
  }

  public void unsetPriority() {
    this.priority = null;
  }

  /** Returns true if field priority is set (has been assigned a value) and false otherwise */
  public boolean isSetPriority() {
    return this.priority != null;
  }

  public void setPriorityIsSet(boolean value) {
    if (!value) {
      this.priority = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TASK_ID:
      if (value == null) {
        unsetTaskId();
      } else {
        setTaskId((Long)value);
      }
      break;

    case CUSTOMER_ID:
      if (value == null) {
        unsetCustomerId();
      } else {
        setCustomerId((String)value);
      }
      break;

    case OVERDUE_AMOUNT:
      if (value == null) {
        unsetOverdueAmount();
      } else {
        setOverdueAmount((Double)value);
      }
      break;

    case OVERDUE_DAYS:
      if (value == null) {
        unsetOverdueDays();
      } else {
        setOverdueDays((Integer)value);
      }
      break;

    case PRIORITY:
      if (value == null) {
        unsetPriority();
      } else {
        setPriority((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TASK_ID:
      return getTaskId();

    case CUSTOMER_ID:
      return getCustomerId();

    case OVERDUE_AMOUNT:
      return getOverdueAmount();

    case OVERDUE_DAYS:
      return getOverdueDays();

    case PRIORITY:
      return getPriority();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TASK_ID:
      return isSetTaskId();
    case CUSTOMER_ID:
      return isSetCustomerId();
    case OVERDUE_AMOUNT:
      return isSetOverdueAmount();
    case OVERDUE_DAYS:
      return isSetOverdueDays();
    case PRIORITY:
      return isSetPriority();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CollectionTask)
      return this.equals((CollectionTask)that);
    return false;
  }

  public boolean equals(CollectionTask that) {
    if (that == null)
      return false;

    boolean this_present_taskId = true;
    boolean that_present_taskId = true;
    if (this_present_taskId || that_present_taskId) {
      if (!(this_present_taskId && that_present_taskId))
        return false;
      if (this.taskId != that.taskId)
        return false;
    }

    boolean this_present_customerId = true && this.isSetCustomerId();
    boolean that_present_customerId = true && that.isSetCustomerId();
    if (this_present_customerId || that_present_customerId) {
      if (!(this_present_customerId && that_present_customerId))
        return false;
      if (!this.customerId.equals(that.customerId))
        return false;
    }

    boolean this_present_overdueAmount = true;
    boolean that_present_overdueAmount = true;
    if (this_present_overdueAmount || that_present_overdueAmount) {
      if (!(this_present_overdueAmount && that_present_overdueAmount))
        return false;
      if (this.overdueAmount != that.overdueAmount)
        return false;
    }

    boolean this_present_overdueDays = true;
    boolean that_present_overdueDays = true;
    if (this_present_overdueDays || that_present_overdueDays) {
      if (!(this_present_overdueDays && that_present_overdueDays))
        return false;
      if (this.overdueDays != that.overdueDays)
        return false;
    }

    boolean this_present_priority = true && this.isSetPriority();
    boolean that_present_priority = true && that.isSetPriority();
    if (this_present_priority || that_present_priority) {
      if (!(this_present_priority && that_present_priority))
        return false;
      if (!this.priority.equals(that.priority))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_taskId = true;
    list.add(present_taskId);
    if (present_taskId)
      list.add(taskId);

    boolean present_customerId = true && (isSetCustomerId());
    list.add(present_customerId);
    if (present_customerId)
      list.add(customerId);

    boolean present_overdueAmount = true;
    list.add(present_overdueAmount);
    if (present_overdueAmount)
      list.add(overdueAmount);

    boolean present_overdueDays = true;
    list.add(present_overdueDays);
    if (present_overdueDays)
      list.add(overdueDays);

    boolean present_priority = true && (isSetPriority());
    list.add(present_priority);
    if (present_priority)
      list.add(priority);

    return list.hashCode();
  }

  @Override
  public int compareTo(CollectionTask other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTaskId()).compareTo(other.isSetTaskId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskId, other.taskId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCustomerId()).compareTo(other.isSetCustomerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCustomerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.customerId, other.customerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOverdueAmount()).compareTo(other.isSetOverdueAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOverdueAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.overdueAmount, other.overdueAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOverdueDays()).compareTo(other.isSetOverdueDays());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOverdueDays()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.overdueDays, other.overdueDays);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPriority()).compareTo(other.isSetPriority());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriority()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priority, other.priority);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CollectionTask(");
    boolean first = true;

    sb.append("taskId:");
    sb.append(this.taskId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("customerId:");
    if (this.customerId == null) {
      sb.append("null");
    } else {
      sb.append(this.customerId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("overdueAmount:");
    sb.append(this.overdueAmount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("overdueDays:");
    sb.append(this.overdueDays);
    first = false;
    if (!first) sb.append(", ");
    sb.append("priority:");
    if (this.priority == null) {
      sb.append("null");
    } else {
      sb.append(this.priority);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'taskId' because it's a primitive and you chose the non-beans generator.
    if (customerId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'customerId' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'overdueAmount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'overdueDays' because it's a primitive and you chose the non-beans generator.
    if (priority == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'priority' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CollectionTaskStandardSchemeFactory implements SchemeFactory {
    public CollectionTaskStandardScheme getScheme() {
      return new CollectionTaskStandardScheme();
    }
  }

  private static class CollectionTaskStandardScheme extends StandardScheme<CollectionTask> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CollectionTask struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TASK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.taskId = iprot.readI64();
              struct.setTaskIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CUSTOMER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.customerId = iprot.readString();
              struct.setCustomerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OVERDUE_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.overdueAmount = iprot.readDouble();
              struct.setOverdueAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OVERDUE_DAYS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.overdueDays = iprot.readI32();
              struct.setOverdueDaysIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PRIORITY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.priority = iprot.readString();
              struct.setPriorityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTaskId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetOverdueAmount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'overdueAmount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetOverdueDays()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'overdueDays' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CollectionTask struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
      oprot.writeI64(struct.taskId);
      oprot.writeFieldEnd();
      if (struct.customerId != null) {
        oprot.writeFieldBegin(CUSTOMER_ID_FIELD_DESC);
        oprot.writeString(struct.customerId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(OVERDUE_AMOUNT_FIELD_DESC);
      oprot.writeDouble(struct.overdueAmount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(OVERDUE_DAYS_FIELD_DESC);
      oprot.writeI32(struct.overdueDays);
      oprot.writeFieldEnd();
      if (struct.priority != null) {
        oprot.writeFieldBegin(PRIORITY_FIELD_DESC);
        oprot.writeString(struct.priority);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CollectionTaskTupleSchemeFactory implements SchemeFactory {
    public CollectionTaskTupleScheme getScheme() {
      return new CollectionTaskTupleScheme();
    }
  }

  private static class CollectionTaskTupleScheme extends TupleScheme<CollectionTask> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CollectionTask struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.taskId);
      oprot.writeString(struct.customerId);
      oprot.writeDouble(struct.overdueAmount);
      oprot.writeI32(struct.overdueDays);
      oprot.writeString(struct.priority);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CollectionTask struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.taskId = iprot.readI64();
      struct.setTaskIdIsSet(true);
      struct.customerId = iprot.readString();
      struct.setCustomerIdIsSet(true);
      struct.overdueAmount = iprot.readDouble();
      struct.setOverdueAmountIsSet(true);
      struct.overdueDays = iprot.readI32();
      struct.setOverdueDaysIsSet(true);
      struct.priority = iprot.readString();
      struct.setPriorityIsSet(true);
    }
  }

}

